### ISSUE TITLE
Possibly use NumHask.Algebra.Abstract.Field?

### ISSUE THREAD

**Issue by nuttycom** [nccgroup/pairing-bls12381#1]
Thank you so much for this demonstration of how to use Haskell; this has really helped my understanding of the underlying math. I have one minor suggestion - since `Num` is somewhat of an unprincipled typeclass, would you consider using https://hackage.haskell.org/package/numhask-0.5.0/docs/NumHask-Algebra-Abstract-Field.html instead? This should eliminate the need to use `error` in a few places, which I think would be an improvement. NumHask also provides `FromInteger` to complete the operations you've implemented in terms of `Num`.

**Comment by integritychain** [comment]
Thanks for the kind feedback! I am writing more code for other algorithms and will experiment with it...on the surface it looks pretty good. This time around I wanted to keep it ultra simple (with minimal/no dependencies).

**Comment by eschorn1** [comment]
The suggested library adds a significant amount of complexity, which may obscure the (intended) simplicity of the code.
